/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package LudoApplication;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Random;

/**
 *
 * @author Jason
 */
public class LudoFrame extends javax.swing.JFrame {
    
    private Board gameboard = null;
    
    private Point[] squares = null;
    private Point[][] homeSquares = null;
    
    
    private Timer diceTimer = null;
    private TimerTask diceUpdateTask = null;
    private boolean animateDie = false;
    private int dieAnimationTime = 0;
    private int dieRollCount = 0;
    
    private Random random = null;
    
    private DefaultListModel gameLog = null;
    
    /**
     * Creates new form NewJFrame
     */
    public LudoFrame() {
        initComponents();
        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblGreenPawn1 = new javax.swing.JLabel();
        lblGreenPawn2 = new javax.swing.JLabel();
        lblGreenPawn3 = new javax.swing.JLabel();
        lblGreenPawn4 = new javax.swing.JLabel();
        lblYellowPawn1 = new javax.swing.JLabel();
        lblYellowPawn2 = new javax.swing.JLabel();
        lblYellowPawn3 = new javax.swing.JLabel();
        lblYellowPawn4 = new javax.swing.JLabel();
        lblRedPawn1 = new javax.swing.JLabel();
        lblRedPawn2 = new javax.swing.JLabel();
        lblRedPawn3 = new javax.swing.JLabel();
        lblRedPawn4 = new javax.swing.JLabel();
        lblBluePawn1 = new javax.swing.JLabel();
        lblBluePawn2 = new javax.swing.JLabel();
        lblBluePawn3 = new javax.swing.JLabel();
        lblBluePawn4 = new javax.swing.JLabel();
        lblBoard = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Game Log");

        jButton1.setText("Roll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        lblGreenPawn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/GreenPawn.png"))); // NOI18N
        lblGreenPawn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        lblGreenPawn1.setBounds(410, 330, 37, 37);
        jLayeredPane1.add(lblGreenPawn1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblGreenPawn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/GreenPawn.png"))); // NOI18N
        lblGreenPawn2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblGreenPawn2.setBounds(450, 330, 37, 37);
        jLayeredPane1.add(lblGreenPawn2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblGreenPawn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/GreenPawn.png"))); // NOI18N
        lblGreenPawn3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblGreenPawn3.setBounds(410, 370, 37, 37);
        jLayeredPane1.add(lblGreenPawn3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblGreenPawn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/GreenPawn.png"))); // NOI18N
        lblGreenPawn4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblGreenPawn4.setBounds(450, 370, 37, 37);
        jLayeredPane1.add(lblGreenPawn4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblYellowPawn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/YellowPawn.png"))); // NOI18N
        lblYellowPawn1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblYellowPawn1.setBounds(330, 20, 37, 37);
        jLayeredPane1.add(lblYellowPawn1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblYellowPawn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/YellowPawn.png"))); // NOI18N
        lblYellowPawn2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblYellowPawn2.setBounds(370, 20, 37, 37);
        jLayeredPane1.add(lblYellowPawn2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblYellowPawn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/YellowPawn.png"))); // NOI18N
        lblYellowPawn3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblYellowPawn3.setBounds(370, 60, 37, 37);
        jLayeredPane1.add(lblYellowPawn3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblYellowPawn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/YellowPawn.png"))); // NOI18N
        lblYellowPawn4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblYellowPawn4.setBounds(330, 60, 37, 37);
        jLayeredPane1.add(lblYellowPawn4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblRedPawn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/RedPawn.png"))); // NOI18N
        lblRedPawn1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblRedPawn1.setBounds(110, 410, 37, 37);
        jLayeredPane1.add(lblRedPawn1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblRedPawn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/RedPawn.png"))); // NOI18N
        lblRedPawn2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblRedPawn2.setBounds(150, 410, 37, 37);
        jLayeredPane1.add(lblRedPawn2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblRedPawn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/RedPawn.png"))); // NOI18N
        lblRedPawn3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblRedPawn3.setBounds(150, 450, 37, 37);
        jLayeredPane1.add(lblRedPawn3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblRedPawn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/RedPawn.png"))); // NOI18N
        lblRedPawn4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblRedPawn4.setBounds(110, 450, 37, 37);
        jLayeredPane1.add(lblRedPawn4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBluePawn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/BluePawn.png"))); // NOI18N
        lblBluePawn1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblBluePawn1.setBounds(30, 100, 37, 37);
        jLayeredPane1.add(lblBluePawn1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBluePawn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/BluePawn.png"))); // NOI18N
        lblBluePawn2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblBluePawn2.setBounds(70, 100, 37, 37);
        jLayeredPane1.add(lblBluePawn2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBluePawn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/BluePawn.png"))); // NOI18N
        lblBluePawn3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblBluePawn3.setBounds(70, 140, 37, 37);
        jLayeredPane1.add(lblBluePawn3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBluePawn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/BluePawn.png"))); // NOI18N
        lblBluePawn4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lblBluePawn4.setBounds(30, 140, 37, 37);
        jLayeredPane1.add(lblBluePawn4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LudoApplication/Board.png"))); // NOI18N
        lblBoard.setBounds(0, 0, 512, 512);
        jLayeredPane1.add(lblBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New Game");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.setToolTipText("");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // For initializing my own components as netbeans locks the first function.
    private void initComponents2()
    {
        gameboard = Application.gameBoard;
        gameboard.AddGameEventListener(new ActionListener() { public void actionPerformed(ActionEvent evt) { GameEventHandler(evt); } });
        
        diceTimer = new Timer();
        diceUpdateTask = new TimerTask() { public void run() { AnimateDie(); } };
        diceTimer.schedule(diceUpdateTask, 0, 10);
        
        random = new Random();
        
        gameLog = new DefaultListModel();
        jList1.setModel(gameLog);
        
        MouseAdapter pawnMouseAdapter = new MouseAdapter()  { public void mouseEntered(MouseEvent evt) { PawnMouseEntered(evt); }
                                                              public void mouseExited(MouseEvent evt) { PawnMouseExited(evt); }};
        lblRedPawn1.addMouseListener(pawnMouseAdapter);
        lblRedPawn2.addMouseListener(pawnMouseAdapter);
        lblRedPawn3.addMouseListener(pawnMouseAdapter);
        lblRedPawn4.addMouseListener(pawnMouseAdapter);
        lblBluePawn1.addMouseListener(pawnMouseAdapter);
        lblBluePawn2.addMouseListener(pawnMouseAdapter);
        lblBluePawn3.addMouseListener(pawnMouseAdapter);
        lblBluePawn4.addMouseListener(pawnMouseAdapter);
        lblYellowPawn1.addMouseListener(pawnMouseAdapter);
        lblYellowPawn2.addMouseListener(pawnMouseAdapter);
        lblYellowPawn3.addMouseListener(pawnMouseAdapter);
        lblYellowPawn4.addMouseListener(pawnMouseAdapter);
        lblGreenPawn1.addMouseListener(pawnMouseAdapter);
        lblGreenPawn2.addMouseListener(pawnMouseAdapter);
        lblGreenPawn3.addMouseListener(pawnMouseAdapter);
        lblGreenPawn4.addMouseListener(pawnMouseAdapter);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        gameboard.StartGame();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Application.gameBoard.DoRollDicePhase();
    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void PawnMouseEntered(java.awt.event.MouseEvent evt)
    {
        JLabel pawn = (JLabel)evt.getSource();
        pawn.setBorder(BorderFactory.createLineBorder(Color.black, 1, true));
    }
    
    private void PawnMouseExited(java.awt.event.MouseEvent evt)
    {
        JLabel pawn = (JLabel)evt.getSource();
        pawn.setBorder(null);
    }
    
    private void GameEventHandler(ActionEvent evt)
    {
        System.out.println(evt.getActionCommand());
        System.out.println(Application.gameBoard.GetPlayerPhase());
        switch(evt.getActionCommand())
        {
            case "TURNSTART": TurnStartEventHandler(evt); break;
            case "TURNEND": TurnEndEventHandler(evt); break;
            case "PHASESTART": PhaseStartEventHandler(evt); break;
            case "PHASEEND": PhaseEndEventHandler(evt); break;
            case "DIEROLLED": DieRolledEventHandler(evt); break;
            case "PAWNMOVED": PawnMovedEventHandler(evt); break;
        }
    }
    
    private void TurnStartEventHandler(ActionEvent evt)
    {
        String msg = "It is " + gameboard.GetActingPlayer().GetName() + "'s turn.";
        gameLog.addElement(msg);
    }
    
    private void TurnEndEventHandler(ActionEvent evt)
    {
        
    }
    
    private void PhaseStartEventHandler(ActionEvent evt)
    {
        String msg = "";
        Board.PHASE phase = gameboard.GetPlayerPhase();
        
        switch(phase)
        {
            case STARTTURN: break;
            case ROLLDIE: msg = "Please roll the die."; break;
            case MOVEPAWNS: msg = "Please select the pawns to move."; break;
            case ENDTURN: break;
            
        }   
        
        gameLog.addElement(msg);
    }
    
    private void PhaseEndEventHandler(ActionEvent evt)
    {
        Board board = Application.gameBoard;
        
        //if (board.GetPlayerPhase() == Board.PHASE.ROLLDIE)
        //    board.PauseGame() // Wait for die animation to end.
    }
    
    private void DieRolledEventHandler(ActionEvent evt)
    {
        String msg = "The die has been cast.";
        gameLog.addElement(msg);
        
        gameboard.PauseGame();
        PlayDiceAnimation();
    }
    
    private void PawnMovedEventHandler(ActionEvent evt)
    {
        
    }
    
    private void OnDiceAnimationEnd()
    {
        int dieValue = gameboard.GetDie().GetFaceValue();
        String msg = gameboard.GetActingPlayer().GetName();
        msg += " has rolled a " + String.valueOf(dieValue) + ".";
        gameLog.addElement(msg);
        
        jLabel1.setText(String.valueOf(dieValue));
        gameboard.UnpauseGame();
    }
    
    private void PlayDiceAnimation()
    {
        if (animateDie)
            return;
        
        animateDie = true;
        dieAnimationTime = 0;
        dieRollCount = 0;
    }
    
    private void AnimateDie()
    {
        if (!animateDie)
            return;
        
        int rollDelay = 0;
        
        if (dieRollCount > 20)
            rollDelay = 3;
        
        if (dieRollCount > 30)
            rollDelay = 10;
        
        if (dieAnimationTime > rollDelay)
        {
            int sides = gameboard.GetDie().GetSides();
            int next = random.nextInt(sides) + 1;
            jLabel1.setText(String.valueOf(next));

            dieAnimationTime = 0;
            dieRollCount++;
            
            if (dieRollCount >= 35)
            {
                animateDie = false;
                OnDiceAnimationEnd();
            }
        }
        
        dieAnimationTime++;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBluePawn1;
    private javax.swing.JLabel lblBluePawn2;
    private javax.swing.JLabel lblBluePawn3;
    private javax.swing.JLabel lblBluePawn4;
    private javax.swing.JLabel lblBoard;
    private javax.swing.JLabel lblGreenPawn1;
    private javax.swing.JLabel lblGreenPawn2;
    private javax.swing.JLabel lblGreenPawn3;
    private javax.swing.JLabel lblGreenPawn4;
    private javax.swing.JLabel lblRedPawn1;
    private javax.swing.JLabel lblRedPawn2;
    private javax.swing.JLabel lblRedPawn3;
    private javax.swing.JLabel lblRedPawn4;
    private javax.swing.JLabel lblYellowPawn1;
    private javax.swing.JLabel lblYellowPawn2;
    private javax.swing.JLabel lblYellowPawn3;
    private javax.swing.JLabel lblYellowPawn4;
    // End of variables declaration//GEN-END:variables
}
